### ISSUE TITLE
ENOTDIR: not a directory, stat 'workspace.json/node_modules'

### ISSUE THREAD

**Issue by wSedlacek** [nrwl/nx-console#1198]
When attempting to run the `nx.generate` command from the command palette the following error message is thrown.

```
Command 'Nx: generate' resulted in an error (A system error occurred (ENOTDIR: not a directory, stat 'workspace.json/node_modules'))
```

macOS 12.0.1
vscode 1.63.1
nx-console 17.13.1

Error does not occur on 17.12.4

**Comment by wSedlacek** [comment]
I believe the issue is at one of these locations it has the path to `workspace.json` rather than the root of the workspace.

https://github.com/nrwl/nx-console/blob/630ac6ec0929184f98f7526a354bd7ba25bb4e68/libs/vscode/tasks/src/lib/select-generator.ts#L66

https://github.com/nrwl/nx-console/blob/630ac6ec0929184f98f7526a354bd7ba25bb4e68/libs/server/src/lib/utils/read-collections.ts#L14

https://github.com/nrwl/nx-console/blob/630ac6ec0929184f98f7526a354bd7ba25bb4e68/libs/vscode/nx-workspace/src/lib/get-nx-workspace-package.ts#L20-L28

https://github.com/nrwl/nx-console/blob/e193eb8b4f3869f81ecb8587975f4cab13b9549c/libs/server/src/lib/utils/read-projects.ts#L64

https://github.com/nrwl/nx-console/blob/630ac6ec0929184f98f7526a354bd7ba25bb4e68/apps/vscode/src/main.ts#L93

**Comment by Cammisuli** [comment]
now this one is a thinker.. There's only two places that set the workspace path that's stored in the Workspace configuration:
https://github.com/nrwl/nx-console/blob/630ac6ec0929184f98f7526a354bd7ba25bb4e68/apps/vscode/src/main.ts#L198
and 
https://github.com/nrwl/nx-console/blob/630ac6ec0929184f98f7526a354bd7ba25bb4e68/apps/vscode/src/main.ts#L228

The function that did call this was changed recently, but it still only sets the directory instead of the json file.

Do you have a repo that I can look at to reproduce this somehow?

**Comment by Cammisuli** [comment]
potentially fixed with https://github.com/nrwl/nx-console/pull/1199 where it will release as 17.13.2

**Comment by wSedlacek** [comment]
> Do you have a repo that I can look at to reproduce this somehow?

This occurs on any Nx repo, including this one, at least for me.
Simply open the command palette (CMD + SHIFT + P) then type `nx` and select `Nx: generate` and the error occurs right away.

> potentially fixed with #1199 where it will release as 17.13.2

I cloned the repo and built from `master` locally and the issue was still occurring.

**Comment by wSedlacek** [comment]
I used git bisect and this is the commit it spit out

[630ac6ec0929184f98f7526a354bd7ba25bb4e68] feat: use nx utils to read all configuration files (#1184)

**Comment by Cammisuli** [comment]
I suspected it was that commit. Thanks for your help!

**Comment by Cammisuli** [comment]
Please check out 17.13.2 and let me know if that doesn't work. If I don't get a rely back, then I can sleep at night 😅

**Comment by wSedlacek** [comment]
Ay, it's working again!

Thank you very much!
