### ISSUE TITLE
Nx Generate (UI) not working in WebStorm

### ISSUE THREAD

**Issue by uus-dev** [nrwl/nx-console#1903]
## Current Behavior

In the WebStorm IDE I can't use the "Nx Generate (UI)", which opens the UI view to generate libraries, components etc. This has worked before and I can see the "Nx Generate (UI)" button when I right click folders.

Refactor > "Move Nx Project" and Refactor > "Remove Nx Project" still works as well as "Nx: Run Target".

## Expected Behavior

I expect to see the Nx Geneate UI, where you first see a dropdown where you can select what to generate and then after that you can see the full generate window where you can type in the relevant information and choose the relevant options to generate the library, component etc.

## Steps to Reproduce

1. In WebStorm install the "Nx Console" plugin and ensure that the IDE has installed and enabled the plugin
2. Go to any folder and right-click to see the context menu
3. Choose either New > "Nx Generate (UI)" or just directly "Nx Generate (UI)"
4. See that nothing happens

### Failure Logs / Images / Videos

https://github.com/nrwl/nx-console/assets/15202984/be565296-78b4-45a1-85d0-c030cd28dd70

### Environment

- Jetbrains WebStorm version: both 2023.1.4 and 2023.2.3
- Nx Console version: 1.13.1, I also tried to install 1.12.0 and 1.11.1, manually and the experienced the same exact behavior.
- Nx Version:
  - Local: v16.4.0
  - Global: v16.9.1
- `nx report`
  ```
  >  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin-arm64
   yarn   : 3.3.1

   nx (global)        : 16.9.1
   nx                 : 16.4.0
   @nx/js             : 16.4.0
   @nx/jest           : 16.4.0
   @nx/linter         : 16.4.0
   @nx/workspace      : 16.4.0
   @nx/angular        : 16.4.0
   @nx/cypress        : 16.4.0
   @nx/devkit         : 16.4.0
   @nx/eslint-plugin  : 16.4.0
   @nx/plugin         : 16.4.0
   @nx/storybook      : 16.4.0
   @nrwl/tao          : 16.4.0
   @nx/webpack        : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @ngrx/component                  : 16.0.1
   @ngrx/component-store            : 16.0.1
   @ngrx/effects                    : 16.0.1
   @ngrx/entity                     : 16.0.1
   @ngrx/eslint-plugin              : 16.0.1
   @ngrx/schematics                 : 16.0.1
   @ngrx/store                      : 16.0.1
   @ngrx/store-devtools             : 16.0.1
   @nxext/capacitor                 : 16.3.0
   @storybook/angular               : 7.0.23
   @testing-library/angular         : 14.1.1
   ngx-extended-pdf-viewer          : 16.2.0
   ---------------------------------------
  ```

**Comment by MaxKless** [comment]
Hi @uus-dev thanks for reporting this. For me to figure out what's going on here, I need some more info.
Could you provide some logs? 
Go to `Help` > `Diagnostic Tools` > `Debug Log Settings.`.. and then insert `#dev.nx.console:trace`. Then paste the `idea.log` or sections of it when the error happens.

Also the `daemon.log` & `daemon-error.log` would be useful. You can find their location by running `nx daemon --log`

**Comment by clemenscodes** [comment]
I have encountered this error today and the logs stated that I was running a JetBrains IDE with missing JCEF functionality. So I installed the JetBrains IDE with the bundled JetBrainsRuntime (JRE) instead of the regular version that I had installed and the Nx Generate UI was working again.

**Comment by MaxKless** [comment]
Hey that's super useful, thanks! I'll add a check & notification to make this easier to spot in the future.

**Comment by MaxKless** [comment]
Hey @uus-dev can you check whether you get that same log? If it is, you need to run with the bundled JBR as @clemenscodes is saying.
I made a PR to show a notification when this happens.

**Comment by MaxKless** [comment]
I can't see any nx-console specific issues in your log, it looks like something is up with kotlin coroutines? I've updated all dependencies in the hope that this will fix it. 
Could you try manually installing the plugin below? 
Just go to `Settings -> Plugins -> ⚙️` and select `Install Plugin from Disk`
<img width="646" alt="image" src="https://user-images.githubusercontent.com/34165455/277951295-eb7da56e-df70-484a-b21b-29bac8a90ed4.png">

Let me know if that fixes your error
[nx-console-0.0.1.zip](https://github.com/nrwl/nx-console/files/13164169/nx-console-0.0.1.zip)

**Comment by uus-dev** [comment]
> I can't see any nx-console specific issues in your log, it looks like something is up with kotlin coroutines? I've updated all dependencies in the hope that this will fix it. Could you try manually installing the plugin below? Just go to `Settings -> Plugins -> ⚙️` and select `Install Plugin from Disk` <img alt="image" width="646" src="https://user-images.githubusercontent.com/34165455/277951295-eb7da56e-df70-484a-b21b-29bac8a90ed4.png">
> 
> Let me know if that fixes your error [nx-console-0.0.1.zip](https://github.com/nrwl/nx-console/files/13164169/nx-console-0.0.1.zip)

Hey @MaxKless. Sorry for not getting back to you earlier. I tested by manually installing the plugin `nx-console-0.0.1.zip`, and I still got the same issue. Something is up with the kotlin coroutines. It throws and `NoClassDefFoundError` for the `kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt` class:

```
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-2" java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:36)
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:148)
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:117)
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2023-10-31 09:55:48,945 [  39663]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - Caused by: java.lang.ExceptionInInitializerError: Exception java.util.ServiceConfigurationError: kotlinx.coroutines.CoroutineExceptionHandler: com.intellij.openapi.application.impl.CoroutineExceptionHandlerImpl not a subtype [in thread "DefaultDispatcher-worker-2"]
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt.<clinit>(CoroutineExceptionHandlerImpl.kt:24)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:36)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:231)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner.resumeWith(DebugProbesImpl.kt:538)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2023-10-31 09:55:48,946 [  39664]   INFO - STDERR - 	... 4 more
```

**Comment by YannCebron** [comment]
Hi, I'm from the IntelliJ SDK Advocacy team.

It seems the issue is caused by the plugin explicitly bundling Kotlin Coroutines Libraries https://github.com/nrwl/nx-console/blob/master/apps/intellij/build.gradle.kts#L43

Any plugin must build against the bundled Kotlin Coroutines Libraries from the target IDE instead. Please also make sure it is not added via transitive dependencies.

Please also keep the Gradle IntelliJ Plugin always updated to the latest version (currently 1.16.0) https://github.com/nrwl/nx-console/blob/master/apps/intellij/build.gradle.kts#L22.

**Comment by uus-dev** [comment]
@MaxKless Is there an ETA on this bug?

**Comment by uus-dev** [comment]
Hey @MaxKless. I'm just writing here, as I still have issues running the Nx Generate (UI) in Webstorm.

I have just updated my Webstorm to latest version 2024.1.2 (Build #WS-241.15989.105, built on April 23, 2024) 
and my Nx Console plugin to latest version 1.25.0.

Also I have chosen the following Boot Java Runtime for my Webstorm IDE, with JCEF:

<img width="341" alt="image" src="https://github.com/nrwl/nx-console/assets/15202984/4ddfdcc3-fbc0-42d9-b762-e1ab265f6500">

But when I try to access the Nx Generate (UI) nothing happens and the following error shows up in the logs:

```
2024-06-12 00:36:46,296 [ 752748]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-06-12 00:36:46,386 [ 752838]  FINER - #dev.nx.console.nxls.NxlsWrapper - Result from nxls: [NxGenerator(name=@consensus/shared/shared/nx/nx-util-migrations:convert-typescript-private-class-pr
2024-06-12 00:36:46,386 [ 752838]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-39" java.lang.AssertionError
2024-06-12 00:36:46,386 [ 752838]   INFO - STDERR - 	at com.intellij.openapi.util.text.StringUtil.shortenTextWithEllipsis(StringUtil.java:2695)
2024-06-12 00:36:46,386 [ 752838]   INFO - STDERR - 	at com.intellij.openapi.util.text.StringUtil.shortenTextWithEllipsis(StringUtil.java:2709)
2024-06-12 00:36:46,386 [ 752838]   INFO - STDERR - 	at com.intellij.openapi.util.text.StringUtil.shortenTextWithEllipsis(StringUtil.java:2679)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at dev.nx.console.generate.ui.NxGeneratorListCellRenderer.customizeCellRenderer(NxGeneratorListCellRenderer.kt:38)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at dev.nx.console.generate.ui.NxGeneratorListCellRenderer.customizeCellRenderer(NxGeneratorListCellRenderer.kt:14)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:45)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:231)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:206)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:258)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:459)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:469)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:513)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at com.intellij.ui.popup.PopupListAdapter.autoSelect(PopupListAdapter.java:102)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at com.intellij.openapi.ui.popup.PopupChooserBuilder.createPopup(PopupChooserBuilder.java:345)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at dev.nx.console.generate.NxGenerateService$selectGenerator$2$1.invokeSuspend(NxGenerateService.kt:98)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-06-12 00:36:46,387 [ 752839]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1744776794), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@2f08f3a5, Dispatchers.Default]
```

I'm just writing here because this may just be an issue on my end, but I need some help.

**Comment by MaxKless** [comment]
Do you have any custom generators you're using? The issue here is probably that you're using a generator that doesn't have a description. I'll make a PR to handle this better but that's something you could look in to right away.

**Comment by uus-dev** [comment]
> Do you have any custom generators you're using? The issue here is probably that you're using a generator that doesn't have a description. I'll make a PR to handle this better but that's something you could look in to right away.

Sorry for late response. No I'm not using any custom generators.

**Comment by MaxKless** [comment]
I think the generator in the log is `@consensus/shared/shared/nx/nx-util-migrations:convert-typescript-private-class-pr` which seems pretty custom no? 
Either way this should be fixed on the latest version, make sure to update and check it out :)

**Comment by uus-dev** [comment]
> I think the generator in the log is `@consensus/shared/shared/nx/nx-util-migrations:convert-typescript-private-class-pr` which seems pretty custom no? Either way this should be fixed on the latest version, make sure to update and check it out :)

Hi @MaxKless

I got the time to try the latest version out.

I have just updated my Webstorm to latest version 2024.1.5 (Build #WS-241.18034.50, built on June 19, 2024)
and my Nx Console plugin to latest version 1.27.0.

It works fine without custom generators. But when I have my custom generator I still get the following error.

Do you know what the issue is? 

```
2024-07-01 21:21:57,676 [ 940542]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-07-01 21:21:57,774 [ 940640]  FINER - #dev.nx.console.nxls.NxlsWrapper - Result from nxls: [NxGenerator(name=@consensus/nx:angular-library, schemaPath=/Users/uus/Documents/repos/connect/Conne
2024-07-01 21:21:57,775 [ 940641]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-19" java.lang.AssertionError
2024-07-01 21:21:57,775 [ 940641]   INFO - STDERR - 	at com.intellij.openapi.util.text.StringUtil.shortenTextWithEllipsis(StringUtil.java:2695)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.openapi.util.text.StringUtil.shortenTextWithEllipsis(StringUtil.java:2709)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.openapi.util.text.StringUtil.shortenTextWithEllipsis(StringUtil.java:2679)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at dev.nx.console.generate.ui.NxGeneratorListCellRenderer.customizeCellRenderer(NxGeneratorListCellRenderer.kt:39)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at dev.nx.console.generate.ui.NxGeneratorListCellRenderer.customizeCellRenderer(NxGeneratorListCellRenderer.kt:14)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:45)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.ui.popup.PopupListAdapter.autoSelect(PopupListAdapter.java:102)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at com.intellij.openapi.ui.popup.PopupChooserBuilder.createPopup(PopupChooserBuilder.java:345)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at dev.nx.console.generate.NxGenerateService$selectGenerator$2$1.invokeSuspend(NxGenerateService.kt:98)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-07-01 21:21:57,776 [ 940642]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1806946281), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@e4f5796, Dispatchers.Default]
```

**Comment by LayZeeDK** [comment]
By the way, it's correct that the custom generator `@consensus/nx/util-migrations:convert-typescript-private-class-property-to-native-private-field` doesn't have a `description` property in its `schema.json` file as suggested by @MaxKless in https://github.com/nrwl/nx-console/issues/1903#issuecomment-2162382112.

**Comment by MaxKless** [comment]
No it was because the name was too long :) 
Here's a PR fixing it https://github.com/nrwl/nx-console/pull/2210

**Comment by uus-dev** [comment]
I can confirm that the Nx Generate UI is now working in Webstorm. I just tested using version 1.28.2 of the Nx Console plugin.

**Comment by nhhockeyplayer** [comment]
not working with latest webstorm

```
2024-10-11 16:56:10,435 [ 332138]   INFO - #c.i.j.n.n.WorkingDirectoryDependentNpmPackageVersionManager - Version fetched successfully: 1.22.22; command: /usr/local/bin/yarn --version, duration: 187ms
2024-10-11 16:56:38,885 [ 360588]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-10-11 16:56:38,886 [ 360589]   INFO - #dev.nx.console.telemetry.TelemetryService - REQUEST: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 475
-> Content-Type: text/plain; charset=UTF-8
BODY Content-Type: text/plain; charset=UTF-8
BODY START
{"client_id":"633d8413-9708-4770-bf21-ed015fde222b","user_id":"633d8413-9708-4770-bf21-ed015fde222b","timestamp_micros":1728680198885000,"non_personalized_ads":true,"user_properties":{"editor":{"value":"WebStorm 2024.1.5"},"os":{"value":"Mac OS X"},"appversion":{"value":"1.32.2"}},"events":[{"name":"actionTriggered","params":{"engagement_time_msec":"1","session_id":"561e2450-b5f6-4ffd-9bd7-bfd8426db522","debug_mode":null,"action_type":"generate.ui","source":"command"}}]}
BODY END
2024-10-11 16:56:39,065 [ 360768]  FINER - #dev.nx.console.nxls.NxlsWrapper - Error from nxls: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-10-11 16:56:39,066 [ 360769]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-15" org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-10-11 16:56:39,066 [ 360769]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:220)
2024-10-11 16:56:39,066 [ 360769]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:204)
2024-10-11 16:56:39,066 [ 360769]   INFO - STDERR - 	at dev.nx.console.nxls.NxlsWrapper.start$lambda$10$lambda$9(NxlsWrapper.kt:110)
2024-10-11 16:56:39,066 [ 360769]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-10-11 16:56:39,067 [ 360770]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1632488309), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@35c36ccf, Dispatchers.Default]
2024-10-11 16:56:39,098 [ 360801]   INFO - #dev.nx.console.telemetry.TelemetryService - RESPONSE: 204 No Content
METHOD: HttpMethod(value=POST)
FROM: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
COMMON HEADERS
-> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
-> Cache-Control: no-cache, no-store, must-revalidate
-> Content-Length: 0
-> Content-Security-Policy-Report-Only: script-src 'none'; form-action 'none'; frame-src 'none'; report-uri https://csp.withgoogle.com/csp/scaffolding/ascnsrsggc:51:0
-> Content-Type: text/plain
-> Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to=coop_reporting
-> Cross-Origin-Resource-Policy: cross-origin
-> Date: Fri, 11 Oct 2024 20:56:39 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END
2024-10-11 16:56:40,761 [ 362464]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-10-11 16:56:40,761 [ 362464]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files


```

**Comment by nhhockeyplayer** [comment]
I added genwerators to nx.json and project.json to no avail

seems like a attribute is misconfigured and missed along the way

```
    "generators": {
        "@nx/workspace:component": {
            "style": "scss"
        },
        "@nx/angular": {
            "convert-tslint-to-eslint": {
                "removeTSLintIfNoMoreTSLintTargets": true
            }
        },
        "@nx/react": {
            "application": {
                "babel": true,
                "style": "css",
                "linter": "eslint",
                "bundler": "webpack"
            },
            "component": {
                "style": "css"
            },
            "library": {
                "style": "css",
                "linter": "eslint"
            }
        },
        "@nx/next": {
            "application": {
                "linter": "eslint"
            }
        },
        "@nx/nest": {
            "application": {
                "linter": "eslint"
            }
        },
        "@nx/express": {
            "application": {
                "linter": "eslint"
            },
            "library": {
                "linter": "eslint"
            }
        },
        "@nx/workspace": {
            "library": {
                "linter": "eslint"
            }
        },
        "@nx/cypress": {
            "cypress-project": {
                "linter": "eslint"
            }
        },
        "@nx/web": {
            "application": {
                "linter": "eslint"
            }
        },
        "@nx/plugin": {
            "plugin": {
                "linter": "eslint"
            }
        },
        "@nx/node": {
            "application": {
                "linter": "eslint"
            },
            "library": {
                "linter": "eslint"
            }
        },
        "@nx/angular:application": {
            "e2eTestRunner": "cypress",
            "linter": "eslint",
            "style": "scss",
            "unitTestRunner": "jest"
        },
        "@nx/angular:library": {
            "linter": "eslint",
            "unitTestRunner": "jest"
        },
        "@nx/angular:component": {
            "style": "scss"
        }
```

**Comment by nhhockeyplayer** [comment]
well Im almost there its half way up

nx build shared-root-ui-widget  

Been adding things to the project.json for my projects for development options and more

![Image](https://github.com/user-attachments/assets/21a9681a-0913-471a-8596-597c7cfa88c0)

**Comment by nhhockeyplayer** [comment]
nxcloud is a pants wetter
some really good stuff![Image](https://github.com/user-attachments/assets/0b4d1336-a28c-481e-b1eb-9b1682bf1229)

**Comment by MaxKless** [comment]
Please keep the bug reports for this issue in the github issue you've created, like this you will keep pinging others.
