### ISSUE TITLE
NX Console 18.74.5 hangs forever in Cursor 2

### ISSUE THREAD

**Issue by siiron** [nrwl/nx-console#2858]
## Current Behavior

On Windows 11, I have upgraded to Cursor 2, and bumped NX Console to 18.74.5. I hangs forever and is not able to list projects. The same version of NX Console works as expected in VSCode 1.105.1. and Kiro 0.5.0.
I'm using NX 22.0.2. **Downgrading to Nx Console 18.74.4 works in Cursor**.

## Expected Behavior

I expect it to list projects and be able to run tasks from the NX Console gui

## Steps to Reproduce

**Reproduction Repository/Steps:**

- Install Cursor 2 and make sure NX Console 18.74.5 is installed.
- Make sure project is a valid standard monorepo with a nx.json on root.
- Open NX Console and try refreshing workspace - it just hangs forever, never listing projects

### Logs (Required)

**Log Output:**

```
Nx Console logs:

[2025-10-31T13:29:49.876Z] Activating Nx Console (pid 33424) 
Nxls Client - idle
Nxls Client - starting
Telemetry: production
Nxls Client - idle
[2025-10-31T13:29:49.955Z] Registered Nx MCP HTTP server with Cursor on port 9535 
[2025-10-31T13:29:49.955Z] MCP server started on port 9535 
Nxls Client - idle
Nxls Client - starting
Graph Machine - undefined, {"context":{"state":"init","project":null,"error":null},"event":{"type":"xstate.init"},"self":{"xstate$$type":1,"id":"x:0"},"system":{"_snapshot":{"_scheduledEvents":{}},"scheduler":{},"_clock":{}}}
Graph - init
Nxls Client - idle
Nxls Client - starting
Nxls Client - idle
Nxls Client - starting
[2025-10-31T13:29:53.325Z] Nx Console Messaging JSON-RPC server listening on \\.\pipe\nx\C:\Users\RSIIKA~1\AppData\Local\Temp\14020603643961945108\nx-console.sock 
Enabling TypeScript plugin for workspace c:\Dev\Projects\Projectname\repo-name
unable to send telemetry: Unable to connect to https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40. Error: Unexpected token 'm', "m��" is not valid JSONNxls Client - idle
Nxls Client - starting
Nxls Client - idle
[2025-10-31T13:30:15.140Z] Connecting to MCP via streamable http 
[2025-10-31T13:30:15.694Z] IDE provider available and connected 
[2025-10-31T13:30:15.695Z] Registering all Nx MCP tools 
[2025-10-31T13:30:15.695Z] Registered Nx core tools 
[2025-10-31T13:30:20.944Z] Using local Nx package at c:/Dev/Projects/Projectname\repo-name/node_modules/nx/src/utils/nx-cloud-utils 
[2025-10-31T13:30:20.945Z] Registered Nx Cloud tools 
Nxls Client - starting
Nxls Client - idle
[2025-10-31T13:30:22.387Z] Connecting to MCP via streamable http 
[2025-10-31T13:30:22.392Z] IDE provider available and connected 
[2025-10-31T13:30:22.392Z] Registering all Nx MCP tools 
[2025-10-31T13:30:22.392Z] Registered Nx core tools 
[2025-10-31T13:30:22.967Z] Using local Nx package at c:/Dev/Projects/Projectname\repo-name/node_modules/nx/src/utils/nx-cloud-utils 
[2025-10-31T13:30:22.967Z] Registered Nx Cloud tools 
Nxls Client - starting
Nxls Client - idle
Nxls Client - starting
Nxls Client - idle

NX Language Server logs:
[Error - 2:29:51 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:29:51 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:29:53 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:29:56 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:30:21 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:30:23 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:30:29 PM] Nx Language Server client: couldn't create connection to server.
```

In both VSCode and Kiro, I don't get these errors for NX Language Server. They only appear in Cursor.

### Environment

- Nx Console version: 18.74.5
- IDE version (VS Code/IntelliJ/WebStorm/etc): Cursor 2.0.43
- Operating System (Windows/macOS/Linux): Windows 11
- Node.js version: 24.10.0
- NX version: 22.0.2

**Nx Report:**

```
Node           : 24.10.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 11.6.1

nx                     : 22.0.2
@nx/js                 : 22.0.2
@nx/jest               : 22.0.2
@nx/eslint             : 22.0.2
@nx/workspace          : 22.0.2
@nx/angular            : 22.0.2
@nx/cypress            : 22.0.2
@nx/devkit             : 22.0.2
@nx/eslint-plugin      : 22.0.2
@nx/module-federation  : 22.0.2
@nx/next               : 22.0.2
@nx/playwright         : 22.0.2
@nx/plugin             : 22.0.2
@nx/react              : 22.0.2
@nx/rollup             : 22.0.2
@nx/rspack             : 22.0.2
@nx/storybook          : 22.0.2
@nx/vite               : 22.0.2
@nx/web                : 22.0.2
@nx/webpack            : 22.0.2
typescript             : 5.9.3
---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 1.19.4
@analogjs/vitest-angular      : 1.19.4
angular-eslint                : 20.5.0
---------------------------------------
Local workspace plugins:
@projectname/ds-tools-automation
---------------------------------------
Cache Usage: 2.97 MB / 93.06 GB
```

**Comment by Ethirajulu** [comment]
This is happening for me too. Confirmed working fine in vscode.

**Comment by Z3RO-O** [comment]
➕Same happening for me.
@siiron, Thank you for the workaround.

**Comment by lebeast777-jpg** [comment]
This is happening for me too. Confirmed working fine in vscode.

@siiron thanks for the workaround!

**Comment by MaxKless** [comment]
are all of you on windows? I can't reproduce it locally

**Comment by stephenmcm** [comment]
➕ for me too. I'm also on windows 11. My logs look the same as the initial report.

**Comment by Ethirajulu** [comment]
> are all of you on windows? I can't reproduce it locally

I am on Mac
System Version:	macOS 26.0.1 (25A362)
Kernel Version:	Darwin 25.0.0

**Comment by rokasAtDashFi** [comment]
On mac (macOS 15.7.1) here as well, same problem.

Cursor version
```
Version: 2.0.60 (Universal)
VSCode Version: 1.99.3
Commit: c6d93c13f57509f77eb65783b28e75a857b74c00
Date: 2025-11-05T00:50:54.645Z (7 hrs ago)
Electron: 37.7.0
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 24.6.0
```
Nx Console version `18.76.3`

**Comment by lebeast777-jpg** [comment]
> are all of you on windows? I can't reproduce it locally

i'm on Win 11

**Comment by PikPakPik** [comment]
Same on Cursor : 
```
Version: 2.0.64
VSCode Version: 1.99.3
Commit: 25412918da7e74b2686b25d62da1f01cfcd27680
Date: 2025-11-06T04:35:14.424Z (1 day ago)
Electron: 37.7.0
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 25.0.0
```

**Comment by guido-marinho** [comment]
> Todos vocês usam Windows? Não consigo reproduzir o problema localmente.
The same problem happens to me on my Mac

**Comment by MaxKless** [comment]
Hey everyone! Sorry for not being super active on here, I just haven't been able to reproduce. 
Can you try again on the latest version of Cursor `2.0.69` as well as the latest version of nx console `18.79.0`?

Thanks!

**Comment by siiron** [comment]
@MaxKless I've tried with Cursor `2.0.69` and NX Console `18.79.0` just now. Same result I'm afraid.

**Comment by MaxKless** [comment]
Are you still getting these?
```[Error - 2:29:51 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:29:51 PM] Nx Language Server client: couldn't create connection to server.
[Error - 2:29:53 PM] Nx Language Server client: couldn't create connection to server.
```

Does it happen for every repo you're in or just some repos? 
^^^ This is the main thing that's interesting to me because it would diffferentiate between a machine setup issue and a repo issue. If it's a repo issue, a minimal repro would be super helpful for me. 

Are you behind a corporate firewall? Some of these connection logs in the original seem like it.

**Comment by PikPakPik** [comment]
@MaxKless No, with all repo i have that in output of Nx Console
```
[2025-11-12T09:04:58.890Z] Error checking provenance: Unexpected token 'm', "m��" is not valid JSON 
unable to send telemetry: Unable to connect to https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40. Error: Unexpected token 'm', "m��" is not valid JSONunable to send telemetry: Unable to connect to https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40. Error: Unexpected token 'm', "m��" is not valid JSON[2025-11-12T09:04:59.265Z] Error checking provenance: Unexpected token 'm', "m��" is not valid JSON 
unable to send telemetry: Unable to connect to https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40. Error: Unexpected token 'm', "m��" is not valid JSONunable to send telemetry: Unable to connect to https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40. Error: Unexpected token 'm', "m��" is not valid JSON
```

And this only on nx repo

> [Error - 2:29:51 PM] Nx Language Server client: couldn't create connection to server.
> [Error - 2:29:53 PM] Nx Language Server client: couldn't create connection to server.

Cursor Version : 
```
Version: 2.0.74 (user setup)
VSCode Version: 1.99.3
Commit: a965544b869cfb53b46806974091f97565545e40
Date: 2025-11-12T00:47:02.205Z
Electron: 37.7.0
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Windows_NT x64 10.0.26100
```

**Comment by MaxKless** [comment]
Okay two more somewhat random questions:
- are you using a custom registry? Or default npm?
- does you package.json have coments in it? Or the `node_modules/nx/package.json` for some reason?

**Comment by PikPakPik** [comment]
default npm
no comments in all package.json

**Comment by MaxKless** [comment]
I just released `18.80.0` that fixes some things in this area (might take a minute to propagate to the cursor extension registry)

Can you try whether this changes anything? Any new errors, still hanging?

**Comment by eXigentCoder** [comment]
Just tested `18.80.0` with Cursor `2.0.69` on MacOS, still hanging for me `18.74.4` did work though

**Comment by MaxKless** [comment]
So strange... looking at https://github.com/nrwl/nx-console/releases/tag/vscode-v18.74.5 the only things that seem like they could have anything to do with this are the MCP sdk upgrade and the skipped minification... 

Do you have any `MCP` logs for me from Cursor? Maybe there's a clue in there

**Comment by PikPakPik** [comment]
Not work :( 

All logs at start of Cursor in Nx Console output :
```
[2025-11-12T22:45:46.868Z] Activating Nx Console (pid 16001) 
Nxls Client - idle
Nxls Client - starting
Telemetry: production
Nxls Client - idle
[2025-11-12T22:45:46.890Z] Registered Nx MCP HTTP server with Cursor on port 9980 
[2025-11-12T22:45:46.890Z] MCP server started on port 9980 
Nxls Client - idle
Nxls Client - starting
Graph Machine - undefined, {"context":{"state":"init","project":null,"error":null},"event":{"type":"xstate.init"},"self":{"xstate$$type":1,"id":"x:0"},"system":{"_snapshot":{"_scheduledEvents":{}},"scheduler":{},"_clock":{}}}
Graph - init
Nxls Client - idle
[2025-11-12T22:45:47.093Z] Nx Console Messaging JSON-RPC server listening on /var/folders/b9/j0q3p4455sj36t5h3202xzqc0000gn/T/12499894862498097700/nx-console.sock 
Enabling TypeScript plugin for workspace /Users/atressel/Documents/Epitech/Projets/T-NAAVI/frontend/web
Nxls Client - starting
[2025-11-12T22:45:47.101Z] unable to send telemetry: Unable to connect to https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40. Error: Unexpected token 'm', "m��" is not valid JSON 
[2025-11-12T22:45:47.105Z] Initializing new MCP session 
Nxls Client - idle
[2025-11-12T22:45:47.130Z] IDE provider available and connected 
Nxls Client - starting
Nxls Client - idle
Nxls Client - starting
Nxls Client - idle

```

And Nx Language Server : 

```
[Error - 11:45:47 PM] Nx Language Server client: couldn't create connection to server.
[Error - 11:45:47 PM] Nx Language Server client: couldn't create connection to server.
[Error - 11:45:47 PM] Nx Language Server client: couldn't create connection to server.
[Error - 11:45:52 PM] Nx Language Server client: couldn't create connection to server.
```

**Comment by thomasserio** [comment]
Could it be a node incompatibility issue? What version does nx need and what version does cursor use?

**Comment by MaxKless** [comment]
It shouldn't be a node incompatibility issue, the node version reported in the original issue description looks fine to me. But please, anyone who reads this and can repro the error, run `nx report` and let me know what it says. There might be some pattern hidden in there. 

Also, I just released a new version of Nx Console with a fix that might help resolve this. I'm not sure because I can't repro so please everyone, install `18.80.1` (might take a bit to show up in cursor's registry mirror) and let me know if the issue persists!

**Comment by thomasserio** [comment]
I got the update and it didn't fix the issue.

NX Report
```
Node           : 23.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.2

nx                     : 20.4.0
@nx/js                 : 20.4.0
@nx/jest               : 20.4.0
@nx/eslint             : 20.4.0
@nx/workspace          : 20.4.0
@nx/cypress            : 20.4.0
@nx/devkit             : 20.4.0
@nx/eslint-plugin      : 20.4.0
@nx/module-federation  : 20.4.0
@nx/react              : 20.4.0
@nx/storybook          : 20.4.0
@nx/vite               : 20.4.0
@nx/web                : 20.4.0
@nx/webpack            : 20.4.0
typescript             : 5.7.3
```


I also see nx-extension-mcp fail with this log:
```
2025-11-13 07:53:01.415 [info] Handling CreateClient action
2025-11-13 07:53:01.415 [info] Creating streamableHttp transport
2025-11-13 07:53:01.416 [info] Connecting to streamableHttp server
2025-11-13 07:53:01.416 [info] No stored tokens found
2025-11-13 07:53:02.864 [info] Handling ListOfferings action, server stored: false
2025-11-13 07:53:02.864 [error] No server info found
2025-11-13 07:53:17.899 [info] Handling CreateClient action
2025-11-13 07:53:17.899 [info] Creating streamableHttp transport
2025-11-13 07:53:17.899 [info] Connecting to streamableHttp server
2025-11-13 07:53:17.899 [info] No stored tokens found
2025-11-13 07:53:19.365 [info] Handling ListOfferings action, server stored: false
2025-11-13 07:53:19.365 [error] No server info found
2025-11-13 07:54:17.807 [info] Client closed for command
2025-11-13 07:54:17.809 [error] Error connecting to streamableHttp server, falling back to SSE: MCP error -32001: Request timed out
2025-11-13 07:54:17.809 [error] Error connecting to streamableHttp server, falling back to SSE: MCP error -32001: Request timed out
2025-11-13 07:54:17.809 [info] Connecting to SSE server
2025-11-13 07:54:17.809 [error] Client error for command This operation was aborted
2025-11-13 07:54:17.811 [info] No stored tokens found
2025-11-13 07:54:17.812 [error] Client error for command This operation was aborted
2025-11-13 07:54:17.812 [error] Client error for command Failed to send cancellation: AbortError: This operation was aborted
2025-11-13 07:54:17.813 [info] No stored tokens found
2025-11-13 07:54:17.818 [error] Client error for command SSE error: Non-200 status code (400)
2025-11-13 07:54:17.818 [error] Error connecting to SSE server after fallback: SSE error: Non-200 status code (400)
2025-11-13 07:54:17.818 [info] Client closed for command
```

**Comment by MaxKless** [comment]
ok on node 23 i'm legitimately not surprised... that's a kind of strange version and I don't think nx supports it officially. Can you change to node 22 or 24? 

There also an nx console setting you can toggle that will show the loaded node version in a notification on editor startup, if you use that we could get some more insights too. 

Thanks!

**Comment by thomasserio** [comment]
I tried on node 24 and 25. Latest nx report:
```
Node           : 25.1.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.6.2

nx                     : 20.4.0
@nx/js                 : 20.4.0
@nx/jest               : 20.4.0
@nx/eslint             : 20.4.0
@nx/workspace          : 20.4.0
@nx/cypress            : 20.4.0
@nx/devkit             : 20.4.0
@nx/eslint-plugin      : 20.4.0
@nx/module-federation  : 20.4.0
@nx/react              : 20.4.0
@nx/storybook          : 20.4.0
@nx/vite               : 20.4.0
@nx/web                : 20.4.0
@nx/webpack            : 20.4.0
typescript             : 5.7.3
```

It's still not working. Also, I ticked that setting but didn't get any notifications, and I've restarted Cursor several times.

I also turned on debug logging in the settings, but all I see in the nx language server output log is:
```
[Error - 9:03:09 AM] Nx Language Server client: couldn't create connection to server.
[Error - 9:03:09 AM] Nx Language Server client: couldn't create connection to server.
[Error - 9:03:09 AM] Nx Language Server client: couldn't create connection to server.
[Error - 9:03:12 AM] Nx Language Server client: couldn't create connection to server.
[Error - 9:03:14 AM] Nx Language Server client: couldn't create connection to server.
[Error - 9:04:31 AM] Nx Language Server client: couldn't create connection to server.
[Error - 9:04:36 AM] Nx Language Server client: couldn't create connection to server.
```

This is the nx console log:
```
[2025-11-13T17:03:09.551Z] Activating Nx Console (pid 29255) 
Nxls Client - idle
Nxls Client - starting
Telemetry: production
Nxls Client - idle
[2025-11-13T17:03:09.567Z] Registered Nx MCP HTTP server with Cursor on port 9416 
[2025-11-13T17:03:09.567Z] MCP server started on port 9416 
Nxls Client - idle
Nxls Client - starting
Graph Machine - undefined, {"context":{"state":"init","project":null,"error":null},"event":{"type":"xstate.init"},"self":{"xstate$$type":1,"id":"x:0"},"system":{"_snapshot":{"_scheduledEvents":{}},"scheduler":{},"_clock":{}}}
Graph - init
Nxls Client - idle
[2025-11-13T17:03:09.836Z] Initializing new MCP session 
[2025-11-13T17:03:09.842Z] IDE provider available and connected 
[2025-11-13T17:03:09.842Z] Registering all Nx MCP tools 
[2025-11-13T17:03:09.842Z] Registered Nx core tools 
[2025-11-13T17:03:09.869Z] Nx Console Messaging JSON-RPC server listening on /var/folders/w8/sf0y1m297v52dy_8xdtlb5pm0000gn/T/15554836455742000960/nx-console.sock 
Enabling TypeScript plugin for workspace /Users/thomasserio/*****
Nxls Client - starting
Nxls Client - idle
[2025-11-13T17:03:09.949Z] Using local Nx package at /Users/thomasserio/*****/node_modules/nx/src/utils/nx-cloud-utils 
[2025-11-13T17:03:09.949Z] Registered Nx Cloud tools 
Nxls Client - starting
Nxls Client - idle
[2025-11-13T17:03:12.212Z] Initializing new MCP session 
[2025-11-13T17:03:12.212Z] IDE provider available and connected 
[2025-11-13T17:03:12.212Z] Registering all Nx MCP tools 
[2025-11-13T17:03:12.212Z] Registered Nx core tools 
[2025-11-13T17:03:12.213Z] Using local Nx package at /Users/thomasserio/*****/node_modules/nx/src/utils/nx-cloud-utils 
[2025-11-13T17:03:12.213Z] Registered Nx Cloud tools 
Nxls Client - starting
Nxls Client - idle
Nxls Client - starting
Nxls Client - idle
Nxls Client - starting
Nxls Client - idle
Nxls Client - starting
Nxls Client - idle
```

I'll try updating my version of nx and see if that helps anything. **Update**: I updated to 22.0.3 and no change.

**Comment by victorrodrigues** [comment]
Hey @MaxKless, 
It's possible that minification introduced in #2852 breaks everything? It disables minification for the vscode project but the nxls project continues to minify files.

The vscode builds depends on the NXLS build with ["params": "foward"](https://github.com/nrwl/nx-console/blob/master/apps/vscode/project.json#L113), but NXLS has its [own configuration for production](https://github.com/nrwl/nx-console/blob/master/apps/nxls/project.json#L83) which still has `minify: true`.

My guess is when the NXLS language server is minified, something breaks in the minified code. The problem likely be in:
- [ensureOnlyJsonRpcStdout function](https://github.com/nrwl/nx-console/blob/master/apps/nxls/src/ensureOnlyJsonRpcStdout.ts) - This function intercepts process.stdout.write to filter JSON-RPC messages. Minification could mangle the function logic or property access.
- JSON-RPC communication setup - The language server client loads nxls/main.js and establishes IPC communication. Minification could break the protocol initialization.

**Comment by MaxKless** [comment]
yes it seems likely... I don't really see how this would happen but it's probably somehow happening. 
https://github.com/nrwl/nx-console/pull/2900
I'll revert it and hope that fixes things

**Comment by thomasserio** [comment]
It seems to be working for me now with the latest update (18.80.2).

**Update**: Wait, no -- it stopped working again. It was working briefly. I was told to restart extensions and it looked like it was working. I reloaded the window (the MCP servers were all red after I restarted extentions) and it stopped again. I'll try quitting and restarting. (another update: restarting Cursor did not help)

**Comment by MaxKless** [comment]
I released a new version `18.80.3` that has the minification back in... maybe try again?

**Comment by victorrodrigues** [comment]
@MaxKless, It worked correctly in version 18.80.3! 🚀 
I tested it on two projects: one newly created and another older project, and it worked on both!

Newly created project with Nx 22.0.3
```
Node           : 24.11.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.6.2

nx (global)            : 22.0.3
nx                     : 22.0.3
@nx/js                 : 22.0.3
@nx/eslint             : 22.0.3
@nx/workspace          : 22.0.3
@nx/devkit             : 22.0.3
@nx/module-federation  : 22.0.3
@nx/react              : 22.0.3
@nx/rollup             : 22.0.3
@nx/web                : 22.0.3
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js
@nx/react
@nx/eslint/plugin
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
```

NXLS Output

```
[Nxls] - 2025-11-18T01:02:05.530Z - Initializing Nx Language Server
[Nxls] - 2025-11-18T01:02:05.533Z - Retrieving workspace configuration for nx 22.0.3
[Nxls] - 2025-11-18T01:02:07.067Z - createProjectGraphAndSourceMapsAsync
[Nxls] - 2025-11-18T01:02:07.579Z - createProjectGraphAndSourceMapsAsync successful
[Nxls] - 2025-11-18T01:02:07.581Z - Resetting daemon client
[Nxls] - 2025-11-18T01:02:07.581Z - Retrieved workspace configuration in: 2048.047709 ms
[Nxls] - 2025-11-18T01:02:07.751Z - Initializing daemon watcher 
[Nxls] - 2025-11-18T01:02:07.764Z - Initialized daemon watcher
```

Cursor version

```
Version: 2.0.77 (Universal)
VSCode Version: 1.99.3
Commit: ba90f2f88e4911312761abab9492c42442117cf0
Date: 2025-11-13T23:10:43.113Z
Electron: 37.7.0
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 25.1.0
```

**Comment by MaxKless** [comment]
Nice! Thanks for investigating it :) I don't understand why exactly it was broken but... well if it's fixed haha
